const actionTypes = {
	LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
	LOGIN_FAILED: 'LOGIN_FAILED',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	ADD_BOOK: 'ADD_BOOK',
	DELETE_BOOK: 'DELETE_BOOK',
	EDIT_BOOK: 'EDIT_BOOK',
};

export default actionTypes;
