const actionTypes = {
    LOGIN_IN_PROGRESS: 'LOGIN_IN_PROGRESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER_IN_PROGRESS: 'REGISTER_IN_PROGRESS',
    REGISTER_FAILED: 'REGISTER_FAILED',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    ADD_BOOK: 'ADD_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
    EDIT_BOOK: 'EDIT_BOOK',
    ADD_SESSION: 'ADD_SESSION',
    DELETE_SESSION: 'DELETE_SESSION',
};

export default actionTypes;
